job_environments:
  common_environment: &common_environment
    CONTAINER_PREFIX: planet4-handbook
    PARENT_IMAGE: gcr.io/planet-4-151612/handbook
    MAX_REPLICA_COUNT: 1
    MIN_REPLICA_COUNT: 1
  develop_environment: &develop_environment
    APP_ENVIRONMENT: development
    APP_HOSTNAME: planet4-dev.greenpeace.org
    APP_HOSTPATH: handbook
    CLOUDSQL_INSTANCE: p4-develop-k8s
    GCLOUD_CLUSTER: p4-development
    GOOGLE_PROJECT_ID: planet-4-151612
    HELM_NAMESPACE: develop
    HELM_RELEASE: planet4-handbook
    NEWRELIC_APPNAME: P4 Handbook Development
    WP_DB_NAME: planet4-handbook_wordpress_develop
    WP_STATELESS_BUCKET: planet4-handbook-stateless-develop
  release_environment: &release_environment
    APP_ENVIRONMENT: staging
    APP_HOSTNAME: planet4-stage.greenpeace.org
    APP_HOSTPATH: handbook
    CLOUDSQL_INSTANCE: planet4-prod
    GCLOUD_CLUSTER: planet4-production
    GOOGLE_PROJECT_ID: planet4-production
    HELM_NAMESPACE: handbook
    HELM_RELEASE: planet4-handbook-release
    NEWRELIC_APPNAME: P4 Handbook Release
    WP_DB_NAME: planet4-handbook_wordpress_release
    WP_STATELESS_BUCKET: planet4-handbook-stateless-release
  production_environment: &production_environment
    APP_HOSTNAME: planet4.greenpeace.org
    APP_HOSTPATH: handbook
    CLOUDSQL_INSTANCE: planet4-prod
    GCLOUD_CLUSTER: planet4-production
    GOOGLE_PROJECT_ID: planet4-production
    HELM_NAMESPACE: handbook
    HELM_RELEASE: planet4-handbook-master
    NEWRELIC_APPNAME: P4 Handbook Production
    WP_DB_NAME: planet4-handbook_wordpress_master
    WP_STATELESS_BUCKET: planet4-handbook-stateless
